# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - name: Install dependencies
#         run: npm install
#         cache:
#           paths: 
#             - node_modules
#             - dist
#       - name: Build
#         run: npm run build

#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - name: Install dependencies
#         run: npm install
#       - name: SonarQube Scan
#         uses: sonarsource/sonarcloud-github-action@v1.5
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#   predeploy:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - name: Install Netlify CLI
#         run: npm install -g netlify-cli
#       - name: Prepare for deployment
#         run: |
#           cp netlify.toml dist/
#           cd dist

#   deploy:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - name: Install dependencies
#         run: npm install
#       - name: Deploy to Netlify
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#         run: npm run deploy --prod --dir=dist --site=$NETLIFY_SITE_ID