stages:
  - build
  - test
  - predeploy
  - setup
  - deploy

image: node
cache:
  paths:
    - "node_modules"
    - "dist"

build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build


test:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    sonar-scanner

predeploy:
  stage: predeploy
  before_script:
    - npm install -g netlify-cli
  script:
    - cp netlify.toml dist/
    - cd dist
  only:
    - master

setup:
  stage: setup
  script:
    - git config user.email "tommy.requillard@gmail.com"
    - git config user.name "tommy.requillard"

deploy:
  stage: deploy
  before_script:
    - npm install
    - export NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN
    - export NETLIFY_SITE_ID=$NETLIFY_SITE_ID
  script:
    - echo "REACT_APP_BASE_URL=https://reactwebdevcv.netlify.app/.netlify/functions/api" >> ".env"
    - npm install --legacy-peer-deps
    - netlify deploy --dir "build" --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --prod
  only:
    - master
