stages:
  - test
  - deploy

test:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner

deploy:
  stage: deploy
  image: node:latest
  before_script:
    - npm install
    - npm install -g netlify-cli
  script:
    - npm run build
    - cp netlify.toml dist/
    - cd dist
    - git add .
    - git push --force --quiet "https://${CI_JOB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}"
  only:
    - master