stages:
  - test
  - deploy

variables:
  SONAR_TOKEN: "6801c799ab4f8a6c2f91e4778d9f5cabd843377e"

test:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner

deploy:
  stage: deploy
  image: node:latest
  before_script:
    - npm install -g netlify-cli
  script:
    - cp netlify.toml dist/
    - cd dist
    - git init
    - git config user.name "GitLab CI"
    - git config user.email "gitlab-ci@example.com"
    - git add .
    - git commit -m "Deploy to gh-pages"
    - git push --force --quiet "https://${CI_JOB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}"
  only:
    - master