stages:
  - test
  - setup
  - predeploy
  - build
  - deploy

image: node

cache:
  paths:
    - "node_modules"
    - "dist"

test:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner

setup:
  stage: setup
  script:
    - git config user.email "tommy.requillard@gmail.com"
    - git config user.name "tommy.requillard"

predeploy:
  stage: predeploy
  before_script:
    - npm install
  script:
    - cp netlify.toml dist/
  only:
    - master

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths: 
      - build/
  only:
    - master

deploy:
  stage: deploy
  image: node:latest
  before_script:
    - npm install -g netlify-cli
    - npm install
  script:
    - echo "REACT_APP_BASE_URL=https://reactwebdevcv.netlify.app/.netlify/functions/api" >> ".env"
    - netlify deploy --dir "build" --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --prod
  only:
    - master
  dependencies:
    - build
