name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurer Git
        run: |
          git config user.email "tommy.requillard@gmail.com"
          git config user.name "tommy.requillard"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        cache:
          paths:
            - node_modules
            - dist
      - name: Build
        run: npm run build

  predeploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Prepare for deployment
        run: |
          cp netlify.toml dist/
          cd dist

  deploy:
    needs: [test, setup, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Utiliser Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Installer les dépendances
        run: |
          npm ci
          npm install -g netlify-cli
      - name: Définir la variable d'environnement
        run: echo "REACT_APP_BASE_URL=https://reactwebdevcv.netlify.app/.netlify/functions/api" >> $GITHUB_ENV
      - name: Télécharger l'artefact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Lister le contenu du répertoire build
        run: ls -la dist/
      - name: Déployer sur Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify link --id $NETLIFY_SITE_ID
          netlify deploy --dir "dist" --auth $NETLIFY_AUTH_TOKEN --prod
